# What is Naive Bayes Algorithm
### It is a classification technique based on Bayes’ Theorem with an independence assumption among predictors. In simple terms, a Naive Bayes classifier assumes that the presence of a particular feature in a class is unrelated to the presence of any other feature.
### Naive Bayes is known for its simplicity, efficiency, and effectiveness in handling high-dimensional data. It is commonly used in various applications, including text classification, spam detection, and sentiment analysis.

## Bayes Theorem
####  P(A|B)=(P(A) * P(B|A))/ P(B)
### In this equation, using Bayes theorem, we can find the probability of A, given that B occurred. A is the hypothesis, and B is the evidence.
####  P(B|A) is the probability of B given that A is True.
####  P(A) and P(B) are the independent probabilities of A and B.

### Important terms in Naive Bayes
####  Prior Probability (P(A)) : Initial belief before seeing the data.
#### Likelihood (P(B|A)) : Probability of the evidence given the hypothesis.
#### Marginal Likelihood (P(B)) : Total probability of the evidence across all hypotheses
####  Posterior Probability (P(A|B) : Updated belief after considering the evidence

## What Are the Assumptions Made by the Naive Bayes Algorithm?
### There are several variants of Naive Bayes, such as Gaussian Naive Bayes, Multinomial Naive Bayes, and Bernoulli Naive Bayes. Each variant has its own assumptions and is suited for different types of data. Here are some assumptions that the Naive Bayers algorithm makes:

### The main assumption is that it assumes that the features are conditionally independent of each other.
### Each of the features is equal in terms of weightage and importance.
### The algorithm assumes that the features follow a normal distribution.
### The algorithm also assumes that there is no or almost no correlation among features.

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [2]:
df=sns.load_dataset('tips')

In [3]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
## independent and dependent features
X=df[['total_bill','tip','smoker','day','time','size']]
y=df['sex']

In [5]:
X.head()

total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [6]:
y=np.where(df['sex']=='Male',1,0)

In [7]:
y

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
l2=LabelEncoder()
l3=LabelEncoder()

In [10]:
X_train['smoker']=l1.fit_transform(X_train['smoker'])
X_train['day']=l2.fit_transform(X_train['day'])
X_train['time']=l3.fit_transform(X_train['time'])

In [11]:
X_test['smoker']=l1.transform(X_test['smoker'])
X_test['day']=l2.transform(X_test['day'])
X_test['time']=l3.transform(X_test['time'])

In [17]:
X_train['smoker'].value_counts()

smoker
0    104
1     66
Name: count, dtype: int64

In [12]:
from sklearn.naive_bayes import GaussianNB

In [14]:
GNB=GaussianNB()
GNB.fit(X_train,y_train)
y_pred=GNB.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.6756756756756757
              precision    recall  f1-score   support

           0       0.53      0.36      0.43        25
           1       0.72      0.84      0.77        49

    accuracy                           0.68        74
   macro avg       0.62      0.60      0.60        74
weighted avg       0.66      0.68      0.66        74

[[ 9 16]
 [ 8 41]]


In [21]:
score=y_test-y_pred

In [27]:
score

array([ 0,  0,  0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  1,
        0, -1,  0, -1,  0, -1,  0, -1,  1,  0, -1,  0,  0,  0,  0,  0,  0,
       -1,  0,  0, -1,  0,  0,  0,  0,  0, -1,  1, -1, -1,  0,  1,  0,  0,
        0,  0,  1,  0,  1,  0,  0,  0,  0, -1, -1,  0,  0,  0, -1,  0, -1,
        0,  0,  0,  0,  1, -1])